name: CI

on:
  push:
  pull_request:

jobs:
  swift-build:
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        run: swift build
